[package]
name = "releasedock-cli"
version = "0.2.8"
edition.workspace = true

[[bin]]
name = "releasedock"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
releasedock-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
