[package]
name = "releasedock-core"
version = "0.2.14"
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
directories.workspace = true
flate2.workspace = true
fs2.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
thiserror.workspace = true
tokio.workspace = true
xz2.workspace = true
zip.workspace = true
url.workspace = true

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[dev-dependencies]
tempfile.workspace = true
